declare type UIViewController = any;
declare type UIApplication = any;
declare var UIApplication: any;
declare var UIApplicationDelegate: any;
declare type NSNotification = any;
declare type NSURL = any;
declare var NSURL: any;
declare type UIColor = any;
declare var UIColor: any;
declare type UIButton = any;
declare type UIImage = any;
declare var UIImage: any;
declare type UIImageView = any;
declare var UIImageView: any;
declare type UIViewAnimationCurve = any;
declare var UIViewAnimationCurve: any;
declare type UIBarMetrics = any;
declare var UIBarMetrics: any;
declare type NSForegroundColorAttributeName = any;
declare var NSForegroundColorAttributeName: any;
declare type UINavigationController = any;
declare type UIGestureRecognizer = any;
declare type UILabel = any;
declare type UISwitch = any;
declare type UITextField = any;
declare type UITextView = any;
declare type UIStatusBarStyle = any;
declare var UIStatusBarStyle: any;
declare type UITableView = any;
declare type UITableViewCell = any;

// telerik-ui
declare var TKSideDrawerShadowMode: any;